### ISSUE TITLE
Update the README.md with the other examples

### ISSUE THREAD

**Issue by mathewcst** [tarb/svelte-dnd-list#1]
It would be nice to have the svelte code for the more complex examples (programmatic control and the muppets)

**Comment by tarb** [comment]
Hey man the example pages are available in src/examples and the pages in src/routes :)

**Comment by mathewcst** [comment]
Yeah, I've found them. It was just a suggestion to link them in the README so it's "clerarer". But thanks a lot for this man, it's an awesome lib and the best I've found for my usecase.

**Comment by tarb** [comment]
Thanks! thats a good idea, cant hurt to put a link to the source in the README - even if its just to show that the source is available
