### ISSUE TITLE
$app/env has been renamed to $app/environment

### ISSUE THREAD

**Issue by rhyder** [tarb/svelte-dnd-list#2]
Hey thanks for the work on this lib!

I have updated my app to the latest version of svelte and it seems an import was updated to a new alias so this has become incompatbile.. 

The HorizontalCenterDropZone.ts file uses the old import.

`error during build:
RollupError: "browser" is not exported by "node_modules/@sveltejs/kit/src/runtime/app/env.js", imported by "node_modules/svelte-dnd-list/HorizontalCenterDropZone.js".`

https://svelte.dev/blog/whats-new-in-svelte-september-2022

**Comment by tarb** [comment]
Thanks!
closed in #3
